version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on host to port 80 on container
    volumes:
      - .:/var/www/html  # Mount the current directory to /var/www/html in the container
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public  # Set Apache document root to /var/www/html/public

